<?php

namespace App\Controller;

use App\Annotation\Routing\Permission;
use App\Annotation\Routing\RouteOptions;
use App\Bo\MovimentacaoItemBo;
use App\Entity\Movimentacao;
use App\Entity\MovimentacaoItem;
use App\Enum\EnumServiceType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class MovimentacaoController extends EntityController
{
    #[Permission('admin')]
    public function all(): JsonResponse
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    #[RouteOptions(path: '/movimentacao/{id}/items/save', parameters: ['id'])]
    public function upsertItem(Request $item, int $id): JsonResponse
    {
        /** @var Movimentacao $movimentacao */
        $movimentacao = $this->getBo()->byId($id);
        if (!$movimentacao)
            return $this->json(
                ['message' => "Movimentação não encontrada para o id '$id'"],
                Response::HTTP_NOT_FOUND
            );

        /** @var MovimentacaoItem $movItem */
        $movItem = $this->merge($item, MovimentacaoItem::class);
        $movItem->setMovimentacao($movimentacao);

        /** @var MovimentacaoItemBo $bo */
        $bo = $this->serviceLocator->getServiceInstance(
            EnumServiceType::Bo,
            MovimentacaoItem::class
        );
        $bo->store($movItem);
        return $this->json($movItem);
    }

    #[RouteOptions(parameters: ['id'])]
    public function deleteItem(int $id): JsonResponse
    {
        /** @var MovimentacaoItemBo $bo */
        $bo = $this->serviceLocator->getServiceInstance(
            EnumServiceType::Bo,
            MovimentacaoItem::class
        );
        $item = $bo->byId($id);
        if ($item) $bo->delete($item);
        return $this->json($item);
    }

    #[RouteOptions(path: '/movimentacao/items/{id}', parameters: ['id'])]
    public function getItems(int $id): JsonResponse
    {
        /** @var Movimentacao $movimentacao */
        $movimentacao = $this->getBo()->byId($id);
        return $this->json($movimentacao);
    }
}