<?php

namespace App\Controller;

use App\Annotation\Routing\EntityArgProvider;
use App\Annotation\Routing\RouteOptions;
use App\Bo\MovimentacaoItemBo;
use App\Entity\Model;
use App\Entity\Movimentacao;
use App\Entity\MovimentacaoItem;
use App\Enum\EnumArgProviderMode;
use App\Enum\EnumServiceType;
use Symfony\Bridge\Doctrine\ArgumentResolver\EntityValueResolver;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\ValueResolver;

class MovimentacaoController extends EntityController
{
    #[Permission('admin')]
    public function all(): JsonResponse
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    #[RouteOptions(path: '/movimentacao/{id}/items/save', parameters: ['id'])]
    public function upsertItem(MovimentacaoItem $item, int $id): JsonResponse
    {
        /** @var Movimentacao $movimentacao */
        $movimentacao = $this->getBo()->byId($id);
        if (!$movimentacao)
            return $this->json(
                ['message' => "Movimentação não encontrada para o id '$id'"],
                Response::HTTP_NOT_FOUND
            );
        $item->setMovimentacao($movimentacao);

        /** @var MovimentacaoItemBo $bo */
        $bo = $this->serviceLocator->getServiceInstance(
            EnumServiceType::Bo,
            MovimentacaoItem::class
        );
        $bo->store($item);
        return $this->json($item);
    }

    #[RouteOptions(path: '/movimentacao/delete/item')]
    public function deleteItem(
        #[EntityArgProvider(EnumArgProviderMode::Query)]
        MovimentacaoItem $item
    ): JsonResponse
    {
        $bo = $this->serviceLocator->getServiceInstance(
            EnumServiceType::Bo,
            MovimentacaoItem::class
        );
        $bo->delete($item);
        return $this->json($item);
    }

    #[RouteOptions(path: '/movimentacao/items/{id}', parameters: ['id'])]
    public function getItem(int $id): JsonResponse
    {
        $bo = $this->serviceLocator->getServiceInstance(
            EnumServiceType::Bo,
            MovimentacaoItem::class
        );
        $item = $bo->byId($id);
        return $this->json($item);
    }

//    #[RouteOptions(path: '/movimentacao/del/{id}', parameters: ['id'])]
    public function del(
        #[ValueResolver(EntityValueResolver::class, disabled: true)]
        Model $a
    ): JsonResponse
    {
        return $this->json($this->f());
    }
    private function f(): Model {
        return new Movimentacao();
    }
}