app_index:
    path: /app/index
    controller: 'App\Controller\AppController::index'
app_loadroutes:
    path: /app/loadroutes
    controller: 'App\Controller\AppController::loadRoutes'
home_index:
    path: /home/index
    controller: 'App\Controller\HomeController::index'
home_about:
    path: /home/about
    controller: 'App\Controller\HomeController::about'
