when@dev:
    app_loadroutes:
        path: /
        controller: 'App\Controller\AppController::loadRoutes'
contabil_index:
    path: /contabil/index
    controller: 'App\Controller\ContabilController::index'
contabil_all:
    path: /contabil/all
    controller: 'App\Controller\ContabilController::all'
contabil_new:
    path: /contabil/new
    controller: 'App\Controller\ContabilController::new'
home_index:
    path: /home/index
    controller: 'App\Controller\HomeController::index'
home_about:
    path: /home/about
    controller: 'App\Controller\HomeController::about'
usuario_all:
    path: /usuario/all
    controller: 'App\Controller\UsuarioController::all'
usuario_byid:
    path: '/usuario/byid/{id}'
    controller: 'App\Controller\UsuarioController::byId'
usuario_new:
    path: '/usuario/new/{nome}/{login}/{senha}'
    controller: 'App\Controller\UsuarioController::new'
